import { ArrowUpRight, AudioLines, ShieldAlert } from "lucide-react"
import { Link } from "react-router-dom"
import { motion, useReducedMotion } from "framer-motion"
import Navbar from "../components/Navbar"
import EmptyState from "../components/EmptyState"
import { WavyBackground } from "../components/WavyBackground"

const sampleChecks = [["Unknown caller", "AI voice clone", "High", "84", "2 min ago"], ["Delivery confirmation", "Replay artifact", "Review", "42", "Today, 10:34"], ["Family voice sample", "No strong indicators", "Low", "12", "Yesterday"]]

function Dashboard() {
  const reduceMotion = useReducedMotion()
  return <WavyBackground backgroundFill="#eef3fb" waveOpacity={0.3} speed="slow" colors={["#22d3ee", "#60a5fa", "#818cf8", "#a78bfa"]}><main className="min-h-screen text-ink-slate-600"><Navbar /><section className="mx-auto max-w-6xl px-5 pb-24 pt-12 sm:px-8 sm:pt-16">
    <motion.div initial={reduceMotion ? false : { opacity: 0, y: 14 }} animate={reduceMotion ? false : { opacity: 1, y: 0 }} transition={{ duration: 0.45 }} className="flex flex-col gap-5 border-b border-[#d4dbe7] pb-8 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#5876a5]">Prototype workspace</p><h1 className="mt-3 font-display text-3xl font-semibold tracking-[-0.04em] text-ink-900 sm:text-4xl">Call dashboard</h1><p className="mt-3 max-w-xl text-sm leading-6 text-[#647188]">Track recent checks and focus attention on the calls that need a safer follow-up.</p></div><div className="inline-flex items-center gap-2 self-start rounded-full border border-[#cfd9ea] bg-white/85 px-4 py-2 text-xs font-medium text-[#506078]"><span className="h-2 w-2 rounded-full bg-[#3f82f1]" />Demo activity</div></motion.div>
    <div className="mt-8 grid gap-4 sm:grid-cols-3">{[["3", "Checks in this demo"], ["1", "Needs review"], ["92%", "Latest confidence"]].map(([value, label], index) => <motion.div key={label} initial={reduceMotion ? false : { opacity: 0, y: 14 }} animate={reduceMotion ? false : { opacity: 1, y: 0 }} transition={{ duration: 0.45, delay: reduceMotion ? 0 : 0.08 + index * 0.08 }} className="rounded-2xl border border-[#d7ddea] bg-white/90 p-5 shadow-[0_10px_30px_rgba(34,52,81,0.05)]"><p className="font-mono text-3xl font-medium tracking-[-0.07em] text-[#20304c]">{value}</p><p className="mt-2 text-sm text-[#718097]">{label}</p></motion.div>)}</div>
    <motion.div initial={reduceMotion ? false : { opacity: 0, y: 16 }} animate={reduceMotion ? false : { opacity: 1, y: 0 }} transition={{ duration: 0.5, delay: reduceMotion ? 0 : 0.28 }} className="mt-7 overflow-hidden rounded-[1.5rem] border border-[#d7ddea] bg-white/90 shadow-[0_16px_40px_rgba(34,52,81,0.07)]"><div className="flex items-center justify-between border-b border-[#e6eaf0] px-5 py-5 sm:px-6"><div><h2 className="font-display text-lg font-semibold text-[#24324b]">Recent checks</h2><p className="mt-1 text-xs text-[#718097]">Prototype data while backend integration is in progress.</p></div><AudioLines className="h-5 w-5 text-[#5c8ee0]" /></div><div className="divide-y divide-[#e9edf3]">{sampleChecks.map(([caller, classification, risk, score, time], index) => <motion.div key={caller} whileHover={reduceMotion ? {} : { backgroundColor: "rgba(241, 246, 255, 0.9)" }} className="flex flex-col gap-4 px-5 py-5 sm:flex-row sm:items-center sm:justify-between sm:px-6"><div className="flex items-center gap-3"><span className={`grid h-10 w-10 place-items-center rounded-xl ${index === 0 ? "bg-[#fff0ea] text-[#c85b49]" : "bg-[#edf4ff] text-[#4a7ed3]"}`}>{index === 0 ? <ShieldAlert className="h-5 w-5" /> : <AudioLines className="h-5 w-5" />}</span><div><p className="text-sm font-semibold text-[#2f3d57]">{caller}</p><p className="mt-1 text-xs text-[#758197]">{classification} · {time}</p></div></div><div className="flex items-center justify-between gap-4 sm:justify-end"><span className={`rounded-full px-2.5 py-1 text-[11px] font-semibold ${risk === "High" ? "bg-[#fff0ea] text-[#c75d49]" : risk === "Low" ? "bg-[#eaf8f4] text-[#23816e]" : "bg-[#fff6e8] text-[#b97928]"}`}>{risk} · {score}</span><Link to={`/call/${index + 1}`} className="inline-flex items-center gap-1 text-xs font-semibold text-[#4e79bd] transition hover:text-[#1f4e96]">View <ArrowUpRight className="h-3.5 w-3.5" /></Link></div></motion.div>)}</div></motion.div>
    <motion.div initial={reduceMotion ? false : { opacity: 0 }} animate={reduceMotion ? false : { opacity: 1 }} transition={{ delay: reduceMotion ? 0 : 0.42 }}><EmptyState className="mt-8 bg-white/70" title="More call history will appear here" description="Connect the analysis backend to replace this demonstration activity with live results." /></motion.div>
  </section></main></WavyBackground>
}

export default Dashboard
